# Generated by Django 4.2.1 on 2023-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-lastname'],
            },
        ),
    ]
